name: build-flatpak

on:
  push:
    branches:
     - main
  pull_request: 
    branches:
     - main

  workflow_dispatch:


jobs:

  Building_PokeMMO:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: Initialize enviornment
        run: |
          sudo apt-get update
          sudo apt install -y flatpak flatpak-builder

      - name: Build flatpak
        run: |
          git config --global protocol.file.allow always
          mkdir -vp ${GITHUB_WORKSPACE}/local
          mkdir -vp ${GITHUB_WORKSPACE}/pokemmo
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          flatpak-builder --user --force-clean --install-deps-from=flathub --install-deps-from=flathub-beta --repo=${GITHUB_WORKSPACE}/local ${GITHUB_WORKSPACE}/pokemmo io.github.pokemmo.yml

      - name: Create Bundle
        run: |
          flatpak build-bundle ${GITHUB_WORKSPACE}/local PokeMMO.flatpak io.github.pokemmo

      - name: Generate version info
        id: version
        run: |
          REL_VER="$( git rev-parse --short HEAD )"
          echo "REL_VER=$REL_VER" >> $GITHUB_ENV
          echo "Welcome to another PokeMMO release based on branch $REL_VER" >> "body.md"

      - name: Publish the flatpak in a new release
        uses: ncipollo/release-action@v1
        env:
          REL_VER: ${{ env.REL_VER }}
        with:
          tag: ${{ env.REL_VER }}
          name: "PokeMMO (${{ env.REL_VER }})"
          bodyFile: "body.md"
          artifacts: "PokeMMO.flatpak"
          allowUpdates: true
          makeLatest: true
          token: ${{ secrets.TRIGGER_BUILD_TOKEN }}